[project]
name = "image-vector-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Manabu TERADA", email = "terada@cmscom.jp" }
]
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.4",
    "numpy>=2.4.2",
    "pillow>=12.1.0",
    "protobuf>=6.33.5",
    "scipy>=1.17.0",
    "sentencepiece>=0.2.1",
    "torch>=2.10.0",
    "transformers>=5.0.0",
]

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "accelerate>=1.12.0",
    "datasets>=4.5.0",
    "ipywidgets>=8.1.8",
    "jupyterlab>=4.5.3",
    "matplotlib>=3.10.8",
    "opencv-python>=4.13.0.90",
    "pandas>=3.0.0",
    "pytest>=9.0.2",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
]
